---
title: "DE_analysis"
output: html_document
date: "2022-11-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r Creat list-column to store datasets }
getwd()
Refract_df<-tribble(~"Rep",~"Depth",~"DASH",~"PATH",
                 "1","100M","untreated","~/DASH_rep/Analysis/CellRanger_output/rep1_100M/outs/raw_feature_bc_matrix",
                 "2","100M","untreated","~/DASH_rep/Analysis/CellRanger_output/rep2_100M/outs/raw_feature_bc_matrix",
                 "3","100M","untreated","~/DASH_rep/Analysis/CellRanger_output/rep3_100M/outs/raw_feature_bc_matrix",
                 "1","100M","DASH","~/DASH_rep/Analysis/CellRanger_output/rep1_dash_100M/outs/raw_feature_bc_matrix",
                 "2","100M","DASH","~/DASH_rep/Analysis/CellRanger_output/rep2_dash_100M/outs/raw_feature_bc_matrix",
                 "3","100M","DASH","~/DASH_rep/Analysis/CellRanger_output/rep3_dash_100M/outs/raw_feature_bc_matrix"
                 )
Refract_df<-Refract_df %>% mutate(Seurat.mat=map(PATH,Read10X))
```

```{r}
source("~/Rfunction/scTheme.R")
# fonts, sizes, etc.
small.font = 6*2
big.font = 6*2
line.width = 0.5*2
pt.size=0.01*2
pt.stroke=0.3*2
label.size=2*2

scTheme <- scThemes(
  small.font = small.font,
  big.font = big.font,
  line.width = line.width,
  pt.size=pt.size,
  pt.stroke=pt.stroke,
  label.size=label.size
)

```

```{r Creat Seurat obj with matrix and name by conditions}
CreateSeuratObject_bySample<-function(count,project_name){
  return(CreateSeuratObject(counts = count, project = project_name,min.features = 200))
}

Refract_df<-Refract_df %>%
  mutate(Name=paste0(Rep,"_",DASH,"_",Depth)) %>% 
  mutate(Seurat.obj=map2(Seurat.mat,Name,~CreateSeuratObject_bySample(count =.x,project_name = .y)))
```

```{r}
merge_refact<-merge(Refract_df$Seurat.obj[[1]],y=Refract_df$Seurat.obj[2:6],add.cell.ids =Refract_df$Name,project="refreaction")
```

```{r}
merge_refact@meta.data <- merge_refact@meta.data %>% mutate(ID=rownames(merge_refact@meta.data)) %>% separate(ID,into=c("rep","DASH","Depth","Cell_ID"),sep="_") 
```

```{r}
common_Cell_ID <- readRDS("~/DASH_rep/Analysis/Venn_common_cell_ID/common_Cell_ID.rds")

merge_refact$Cell <-ifelse(merge_refact$rep=="1",ifelse(merge_refact$Cell_ID%in%common_Cell_ID[[1]],"Cell","Non-cell"),ifelse(merge_refact$rep=="2",ifelse(merge_refact$Cell_ID%in%common_Cell_ID[[2]],"Cell","Non-cell"),ifelse(merge_refact$rep=="3",ifelse(merge_refact$Cell_ID%in%common_Cell_ID[[3]],"Cell","Non-cell"),"NULL")))

```

```{r}
merge_refact<-subset(merge_refact,subset=Cell=="Cell")
```

```{r}
merge_refact$DASH<-merge_refact$DASH %>% as.factor()
Idents(merge_refact)<-merge_refact$DASH
```

```{r}
merge_refact<-merge_refact %>% NormalizeData() %>% FindVariableFeatures() %>% ScaleData()
```


```{r}
DE_ranks_sum<-FindAllMarkers(merge_refact,logfc.threshold = 0,only.pos = T)
```

```{r}
DE_ranks_sum<-DE_ranks_sum %>% mutate(avg_log2FC=ifelse(cluster=="untreated",-avg_log2FC,avg_log2FC))
DE_ranks_sum<-DE_ranks_sum %>% mutate(log10_adj=ifelse(is.infinite(-log10(p_val_adj)),708.3964,-log10(p_val_adj)))
DE_ranks_sum<-DE_ranks_sum %>% mutate(sig=ifelse((abs(avg_log2FC)>1) & (log10_adj>-log10(0.05)),"Sig","nonSig"))

DE_ranks_sum$sig %>% table

saveRDS(DE_ranks_sum,"DE_ranks_sum.rds")
```

```{r}
pdf("DE.volcano.pdf", height = 3, width = 5, compress = F)
DE_ranks_sum %>%ggplot(aes(x=avg_log2FC,y=log10_adj))+
  geom_point(mapping=aes(color=sig,))+
  scale_color_manual(values = c("nonSig" = "black", "Sig" = "red"))+
  geom_hline(yintercept = log10(5),linetype="dotted")+
  geom_vline(xintercept = c(-1,1),linetype="dotted")+
  scale_x_continuous(limits=c(-12,12))+
  ylab(label="-log10(p-adj)")+
  scTheme$scatter+
  theme(axis.line = element_line(colour = "black"),
    panel.border = element_blank())
  
dev.off()
```
```{r}
DE_ranks_sum_raw<-FindAllMarkers(merge_100M,logfc.threshold = 0,only.pos = T,slot = "count")
```

```{r}
DE_ranks_sum_raw<-DE_ranks_sum_raw %>% mutate(avg_log2FC=ifelse(cluster=="untreated",-avg_log2FC,avg_log2FC))
```

```{r}
DE_ranks_sum_raw %>%ggplot(aes(x=avg_log2FC,y=-log10(p_val_adj)))+geom_point()+
  geom_hline(yintercept = log10(5),linetype="dotted")+
  geom_vline(xintercept = c(-1,1),linetype="dotted")+
  scTheme$scatter
```

```{r}
merge_100M.mat<-merge_100M@assays$RNA@counts
merge_100M.no.16S.mat<-merge_100M.mat[-c(which(rownames(merge_100M.mat)=="16S-rRNA")),]
```

```{r}
merge_100M.no.16S<-CreateSeuratObject(counts = merge_100M.no.16S.mat,meta.data = merge_100M@meta.data,min.features = 200)
Idents(merge_100M.no.16S)<-merge_100M.no.16S$DASH
```

```{r}
DE_ranks_sum_no.16S<-FindAllMarkers(merge_100M.no.16S,logfc.threshold = 0,only.pos = T,slot = "count")
```

```{r}
DE_ranks_sum_no.16S<-DE_ranks_sum_no.16S %>% mutate(avg_log2FC=ifelse(cluster=="untreated",-avg_log2FC,avg_log2FC))
```

```{r}
DE_ranks_sum_no.16S %>%ggplot(aes(x=avg_log2FC,y=-log10(p_val_adj)))+geom_point()+
  geom_hline(yintercept = log10(5),linetype="dotted")+
  geom_vline(xintercept = c(-1,1),linetype="dotted")+
  theme_classic()+
  scale_x_continuous(limits = c(-2,2))

```

```{r}
saveRDS(DE_ranks_sum,"DE_ranks_sum.rds")
saveRDS(DE_ranks_sum_no.16S,"DE_ranks_sum_no.16S.rds")

```

```{r}
saveRDS(merge_refact,"merge_100M.rds")
```

